#Defined in gradle.properties
#loom_version = "1.15-SNAPSHOT"
#kotlin_version = "2.3.20"
#ksp_version = "2.3.6"

#RFU
mod.version = "1.8.1"
mod.group = "cloud.glitchdev.rfu"
mod.id = "rfu"
mod.name = "RiccioFishingUtils"

#Fabric
deps.fabric_loader = "0.18.4"

#Devauth
devauth_version = "1.2.2"

#Essential
elementa_version = "734"
universalcraft_version = "475"

#Faric_language_kotlin
fabric_language_kotlin = "1.13.10+kotlin.2.3.20"
modrinth.kotlin_version = "1.13.10+kotlin.2.3.20"

["1.21.10"]
#Fabric
deps.fabric_api = "0.138.4+1.21.10"
modrinth.fapi_version = "0.138.4+1.21.10"
#Minecraft
mod.mc_dep = ">=1.21.10 <=1.21.10"
#Essential
universalcraft_mc_version = "1.21.9"
#ResourcefulConfig
resourceful_mc_version = "1.21.9"
resourceful_version = "3.9.2"
resourcefulkt_mc_version = "1.21.5"
resourcefulkt_version = "3.5.16"
#Hypixel Mod API
hypixel_mod_api_version = "1.0.1"
modrinth.hypixel_version = "1.0.1+build.1+mc1.21"

["1.21.11"]
#Fabric
deps.fabric_api = "0.141.1+1.21.11"
modrinth.fapi_version = "0.141.1+1.21.11"
#Minecraft
mod.mc_dep = ">=1.21.11 <=1.21.11"
#Essential
universalcraft_mc_version = "1.21.11"
#ResourcefulConfig
resourceful_mc_version = "1.21.11"
resourceful_version = "3.11.2"
resourcefulkt_mc_version = "1.21.5"
resourcefulkt_version = "3.5.16"
#Hypixel Mod API
hypixel_mod_api_version = "1.0.1"
modrinth.hypixel_version = "1.0.1+build.1+mc1.21"

["26.1"]
#Fabric
deps.fabric_api = "0.144.4+26.1"
modrinth.fapi_version = "0.144.4+26.1"
#Minecraft
mod.mc_dep = ">=26.1 <=26.1.1"
#Essential
universalcraft_mc_version = "26.1"
#ResourcefulConfig
resourceful_mc_version = "26.1"
resourceful_version = "4.0.0"
resourcefulkt_mc_version = "26.1"
resourcefulkt_version = "4.0.0"
#Hypixel Mod API
hypixel_mod_api_version = "1.0.2"
modrinth.hypixel_version = "1.0.2+build.1+mc26.1"

["26.1.1"]
stonecutter.redirect = "26.1"