#Defined in gradle.properties
#loom_version = "1.15-SNAPSHOT"
#kotlin_version = "2.3.20"
#ksp_version = "2.3.6"

#RFU
mod.version = "1.14.0"
mod.group = "cloud.glitchdev.rfu"
mod.id = "rfu"
mod.name = "RiccioFishingUtils"

#Fabric
deps.fabric_loader = "0.18.4"

#Devauth
devauth_version = "1.2.2"

#Essential
elementa_version = "745"
universalcraft_version = "505"

#Faric_language_kotlin
fabric_language_kotlin = "1.13.10+kotlin.2.3.20"
modrinth.kotlin_version = "1.13.10+kotlin.2.3.20"

["26.1"]
#Fabric
deps.fabric_api = "0.144.4+26.1"
modrinth.fapi_version = "0.144.4+26.1"
#Minecraft
mod.mc_dep = ">=26.1 <26.2"
#Essential
universalcraft_mc_version = "26.1"
#ResourcefulConfig
resourceful_mc_version = "26.1"
resourceful_version = "4.0.0"
resourcefulkt_mc_version = "26.1"
resourcefulkt_version = "4.0.0"
#Hypixel Mod API
hypixel_mod_api_version = "1.0.2"
modrinth.hypixel_version = "1.0.2+build.1+mc26.1"

["26.1.1"]
stonecutter.redirect = "26.1"

["26.1.2"]
stonecutter.redirect = "26.1"

["26.2"]
#Fabric
deps.fabric_api = "0.153.0+26.2"
modrinth.fapi_version = "0.153.0+26.2"
#Minecraft
mod.mc_dep = ">=26.2 <26.3"
#Essential
universalcraft_mc_version = "26.2"
#ResourcefulConfig
resourceful_mc_version = "26.2"
resourceful_version = "5.0.0"
resourcefulkt_mc_version = "26.1"
resourcefulkt_version = "4.0.0"
#Hypixel Mod API
hypixel_mod_api_version = "1.0.2"
modrinth.hypixel_version = "1.0.2+build.1+mc26.1"