package cloud.glitchdev.rfu.constants

enum class SeaCreatureCategory(val islands: List<FishingIslands>) {
    GENERAL_WATER(
        listOf(
            FishingIslands.HUB,
            FishingIslands.DESERT,
            FishingIslands.GALATEA,
            FishingIslands.SPIDER,
            FishingIslands.HOLLOWS,
            FishingIslands.BAYOU,
            FishingIslands.PARK
        )
    ),
    GENERAL_LAVA(
        listOf(
            FishingIslands.GALATEA, FishingIslands.HOLLOWS, FishingIslands.ISLE
        )
    ),
    HOTSPOT_WATER(
        listOf(FishingIslands.BAYOU, FishingIslands.HUB, FishingIslands.SPIDER)
    ),
    HOTSPOT_LAVA(
        listOf(FishingIslands.ISLE)
    ),
    OASIS(
        listOf(FishingIslands.DESERT)
    ),
    HOLLOWS(
        listOf(FishingIslands.HOLLOWS)
    ),
    DWARVEN(
        listOf(FishingIslands.DWARVEN)
    ),
    SPOOKY(
        listOf(
            FishingIslands.HUB,
            FishingIslands.DESERT,
            FishingIslands.GALATEA,
            FishingIslands.SPIDER,
            FishingIslands.HOLLOWS,
            FishingIslands.BAYOU,
            FishingIslands.PARK
        )
    ),
    WINTER(
        listOf(FishingIslands.JERRY)
    ),
    SHARK(
        listOf(
            FishingIslands.HUB,
            FishingIslands.DESERT,
            FishingIslands.GALATEA,
            FishingIslands.SPIDER,
            FishingIslands.HOLLOWS,
            FishingIslands.BAYOU,
            FishingIslands.PARK
        )
    ),
    ISLE(
        listOf(FishingIslands.ISLE)
    ),
    GALATEA(
        listOf(FishingIslands.GALATEA)
    ),
    BAYOU(
        listOf(FishingIslands.BAYOU)
    )
}